### ISSUE TITLE
Installation from Plugins Admin doesn't populate QuickText.conf.ini

### ISSUE THREAD

**Issue by pryrt** [vinsworldcom/nppQuickText#11]
When I installed 0.1.1.1 from Plugins Admin of NPP v7.8.4-64bit, and opened **Plugins > QuickText > Options** dialog, the language pulldown menu was completely empty.  **Plugins > QuickText > Open Config File** showed a a completely empty config file.  If I pasted from [`QuickText.conf.default.ini`](https://github.com/vinsworldcom/nppQuickText/blob/master/Config/QuickText.conf.default.ini), saved, exited/reloaded Notepad++, then the language pulldown was correctly populated.

(as mentioned in https://community.notepad-plus-plus.org/post/50377)

**Comment by vinsworldcom** [comment]
This *I think* is an easy fix.  The plugin uses default values for the values it reads from the config file so should work with or without it.  However, I don't think it "saves" those values to the config file.  From other plugins, I usually see a WritePrivateProfileString() under pluginCleanUp() which isn't present here.

I think a small change I may be able to look at this weekend.

**Comment by vinsworldcom** [comment]
Fix in 0.1.2.2 pre-release

**Comment by vinsworldcom** [comment]
Fixed in bade879
