### ISSUE TITLE
Creating multiple new substitutions

### ISSUE THREAD

**Issue by pryrt** [vinsworldcom/nppQuickText#12]
The options dialog doesn't currently make it easy to make multiple new substitution entries.

If you follow the sequence of Options dialog, **Tag** = `new1`, **Substitution Text** = `first text here`, **Add/Modify**, it adds `new1` to the **Tags**-picker list.  But then doing **Tag** = `new2`, **Substitution Text** = `second text here`, **Add/Modify [modified]**, it just renames and modifies the first entry, rather than adding a second entry.  Clicking in the **Tags**-picker list to try to "unselect" the `new1` tag (either by re-clicking `new1` or clicking in the empty area) doesn't work.  I either have to exit the dialog, or at least pick a different language then go back to the original language in order to be able to create a second new substitution.

Ideas:
1) Separate out the **New** and **Modify** into two buttons, so that anytime you hit **New**, it will create a new one rather than rename (grey out **New** if the **Tag:**-name entry hasn't changed to prevent duplicate-named substitutions)
2) Allow re-clicking on the **Tags**-picker list to unselect the active substitution, and clear the **Tag:**-name entry and the **Substitution List** textbox.

**Comment by vinsworldcom** [comment]
Fixed in [0.1.2.3](https://github.com/vinsworldcom/nppQuickText/releases/tag/0.1.2.3)

**Comment by vinsworldcom** [comment]
Fixed in bade879
