### ISSUE TITLE
Delete button doesn't seem to work in GLOBAL language

### ISSUE THREAD

**Issue by pryrt** [vinsworldcom/nppQuickText#13]
When I created a new global substitution, saved, exited Notepad++ (so nothing stuck in memory), reloaded, came back in, and try to delete that substitution, it asks for confirmation; on okay, it drops to previous dialog and shows _nothing_ in the GLOBAL view; OK again anyway.  That substitution still works.  Looking at the Options dialog again still shows that substitution exists.  Try again to delete, but this time do a **QuickText > Refresh Configuration**; the "deleted" substitution still exists and works.

If I use the same sequences in some other language (like INI or USER), the substitution deletes just fine: it immediately prompts for save, the substitution stops working, and it's removed from the Options dialog, so it's presumably a bug in the special handling of the GLOBAL substitutions

**Comment by vinsworldcom** [comment]
The GLOBAL had some issues in the original implementation that I "fixed".  Apparently I didn't fix everything yet!  Be glad they actually work - the original implementation didn't even allow global tags to work at all!

I'll have a look at this one too.

**Comment by vinsworldcom** [comment]
Fix in [0.1.2.2](https://github.com/vinsworldcom/nppQuickText/releases/tag/0.1.2.2) pre-release

**Comment by vinsworldcom** [comment]
Fixed in bade879
Release [0.1.3.1](https://github.com/vinsworldcom/nppQuickText/releases/tag/0.1.3.1)
