### ISSUE TITLE
How do I add another language?

### ISSUE THREAD

**Issue by d-jsb** [vinsworldcom/nppQuickText#18]
I tried to add  a nother language by adding to QuickText.ini like this:
[250]
#LANGUAGE_NAME=NewLanguage
class=class $ {\nprivate:\n	$\nprotected:\n	$\npublic:\n	$\n};\n$
else=else {\n	$\n}\n$

After a config reload the list of languages didn't change. What am I missing?

**Comment by vinsworldcom** [comment]
Your can't randomly add languages.  The language numbers come from Notepad++.  See the README for Notepad++ languages names / numbers.

Better to just add from the GUI: Plugins => Quick Text=> Options...

Cheers.
