### ISSUE TITLE
Crash Notepad++ after apply QT snippet on the 260 char at line

### ISSUE THREAD

**Issue by SooR** [vinsworldcom/nppQuickText#20]
Hello. I'm trying insert some text by a keyword and [ctrl + space ] for submitting, but on the 260 (or more) character npp was crashed w/o any errors.

Npp 7.9.1 x64, win10.
My plugins: 

- DSpellCheck, 
- ElasticTabstops, 
- Explorer, 
- NavigateTo, 
- NppFTP,
- QuickText, 
- XMLTools

**Comment by vinsworldcom** [comment]
I assume you mean the Snippet is more than 260 characters, not that you're trying to insert it into a file at the 260th character at line 20?  What is the snippet?

I have snippets that are about double the 260 characters and they work fine.  Couple of things:

- make sure the Snippet only uses ANSI characters
- try without the other plugins (especially ElasticTabstops and NavigateTo as I have all the other plugins installed and I don't have the issue).

Cheers.
