### ISSUE TITLE
Crash Notepad++ - plugin does not see all settings due to large config file

### ISSUE THREAD

**Issue by UnlimitedChild** [vinsworldcom/nppQuickText#23]
Hi,

if the line is very long, then the editor crashes, when this line is selected in the QuickText settings, here is an example of this line - HBA_SendScsiInquiry_Handle_PortWWN_FcLUN_EVPD_PageCode_pRspBuffer_RspBufferSize_pSenseBuffer_SenseBufferSize=HBA,SendScsiInquiry,Handle,PortWWN,FcLUN,EVPD,PageCode,pRspBuffer,RspBufferSize,pSenseBuffer,SenseBufferSize

If the config file is too big then, it does not load all configuration settings, as a result the plugin doesn't work.

autoCompletion->asm
TestMasm.asm - Test File
QuickText.ini -> Plugins -> Config

[QuickText_Bugs.zip](https://github.com/vinsworldcom/nppQuickText/files/7072507/QuickText_Bugs.zip)

Thanks!

**Comment by vinsworldcom** [comment]
Notepad++ debug info from ?=>Debug Info... please?

I'm on Windows 10 64-bit with Notepad++ 8.1.4 64-bit and to not see an issue.  It is slow, but no crash.

Notepad++ v8.1.4   (64-bit)
Build time : Sep 14 2021 - 01:35:33
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : .\TestMasm.asm
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1165
Current ANSI codepage : 1252
Plugins : QuickText.dll


![image](https://user-images.githubusercontent.com/9657169/133297806-f9664e2c-1219-474b-941c-16b3edd3be18.png)


Cheers.
