### ISSUE TITLE
Search through a file

### ISSUE THREAD

**Issue by PaleFlyer** [vinsworldcom/nppQuickText#25]
I found this plugin as I have to work with some very large text files, which have consistent issues through them, and I was looking for a way to automate fine/replace.  This seems to be everything but the "FIND" part.

I will freely admit I have only been aware of this plugin for like 10 minutes, so might have missed something, but can it work with the search part of find?

I'm talking 8150ish lines for a "small" file.  And it is an odd format most editors screw up, and it isn't all text either, so I can't just run it through a standard spell check system.

**Comment by vinsworldcom** [comment]
This plugin is to insert code snippets.  There is no find / search capability.  You just insert code snippets while typing to save yourself time.  There are other plugins that handle searching / replacing.  There are also scripting languages that may to that better than trying to work it through an editor.

Cheers.
