### ISSUE TITLE
Use tab size from notepad settings

### ISSUE THREAD

**Issue by anjemor** [vinsworldcom/nppQuickText#28]
A tab size of 2 cm/9 characters makes substitution text unreadable and forces the user to scroll - inconvenient.

**Comment by vinsworldcom** [comment]
Please provide more context.  Are you saying you try to use a tab in the substitution text and Notepad++ is not converting it?

**Comment by anjemor** [comment]
No. It's about the substitution text field in the Quicktext settings dialog.

**Comment by vinsworldcom** [comment]
Not sure that's possible - the Substitution Text field is not a Scintilla edit control, it's a simple Windows Edit Text dialog control.  I can't adjust tab sizes with `SCI_` commands.  If you have a way, feel free to submit a PR.

**Comment by anjemor** [comment]
Ok, after digging into this, it seems like Windows doesn't support any easy way to do this without using richedit.
So the best way for me is not to use tabs.
