### ISSUE TITLE
Always allow resizing of dialog windows when programming

### ISSUE THREAD

**Issue by anjemor** [vinsworldcom/nppQuickText#30]
Just use anchors for the substitution text field on the right side, set the border to 'Resizing' to allow resizing of the dialog box, save the new size in configuration and read configuration next time.
This applies to any program ever in the past and future. Even for Microsoft it took 30 years to get this.
Otherwise - inconvenient.

**Comment by vinsworldcom** [comment]
Resizing added for Substitution Text edit control.  Geometry is not remembered on open/close or between Notepad++ relaunch.  If that is needed, happy to accept a pull request.

**Comment by anjemor** [comment]
Thanks for all the changes. 
I was digging into your source code and realized this is going back to 2006. 
Maybe in my vacation I download the 5 GB Visual Studio and make all the pull requests.

**Comment by vinsworldcom** [comment]
Note this isn't actually my code. I rescued this abandoned plug-in because I liked it and added some functionality. I'm not a c++ programmer so just making do with what I can do.

**Comment by anjemor** [comment]
The same goes for me somehow. I abandoned c++ 15 years ago but can work with it.
And I want to help rescue this plugin, too. I need the plugin for lua scripting, so I don't have to install more editors.
