### ISSUE TITLE
Don't ask the user if something is OK after user is pressing OK

### ISSUE THREAD

**Issue by anjemor** [vinsworldcom/nppQuickText#31]
OK means already OK, ok? 
The same goes for 'Cancel'.
Also consider renaming the button to 'Close' and just save. If users don't want to save they press 'Cancel'.

Consider working with

- (more) changing button texts
- changing disabled/enabled property of buttons

on the various actions of users so the user can easily see what is going to happen.

**Comment by vinsworldcom** [comment]
Setting added to confirm on button presses.  Uncheck for no confirmation dialogues.
