### ISSUE TITLE
Button text is turning to 'Modify'

### ISSUE THREAD

**Issue by anjemor** [vinsworldcom/nppQuickText#32]
Button text is turning to 'Modify' on new tag entry when substitution text is entered (onchange event). Instead button text have to stay on 'Add', because user wants still to add the tag.

**Comment by vinsworldcom** [comment]
EN_CHANGE for edit text box.  Simply giving focus to the edit text control seems to trigger this notification for me.  May just revert back to static "Add/Modify" text on the button.
