### ISSUE TITLE
Tags with colon do not work

### ISSUE THREAD

**Issue by cdbdev** [vinsworldcom/nppQuickText#34]
Hi,

First of all, thanks for your work on this nice plugin :-)

I do have 1 issue though. Whenever I try to use a tag with a colon ':' in the word, the snippet does not get called. 

For example I frequently use markdown (UDL) and like to prefix the tags like this:

```
 md:code 
 md:table
```

Is it possible the support colon too?

Thanks

**Comment by vinsworldcom** [comment]
Not by default.  Colon `:` is not a "word character" which is what is valid for tags.  You can try to manually update the config file item `AllowedChars`:

```INI
[General]
AllowedChars=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890._-
```

and add a `:` to it.

1) Plugins => QuickText => Open Config File
2) make the edit described above
3) Save
4) Plugins => QuickText => Refresh Configuration
5) Try your `md:code` tag now.

My testing showed this to work:

```
[General]
AllowedChars=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890._-:
```

![image](https://user-images.githubusercontent.com/9657169/191871539-6796241d-a9a6-4bd0-9d33-a194287a9ff8.png)

**Comment by cdbdev** [comment]
yes, thank you. I tried this already, but forgot 'Refresh Configuration'.
