### ISSUE TITLE
Multiple hotspots don't override default autocompletion

### ISSUE THREAD

**Issue by Clozent** [vinsworldcom/nppQuickText#35]
Using a snippet with multiple hotspots places the cursor on the first hotspot (as intended). The problem arises after pressing Tab to go to the next hotspot. If notepad++ finds an autocompletion for whatever was typed in the first hotspot, it will insert the suggestion, and then go to the next hotspot.

**Comment by vinsworldcom** [comment]
Probably shouldn't use Tab as your QuickText trigger.  There are known issues / limitations with it.  At one point it was tried to address this and some issues were resolved, but I'm afraid I can't override when Notepad++ / Scintilla compete for the function of a hotkey configured to do 2 different things.
